// The Starred Bill: London's Michelin-starred restaurants.
// Stars and addresses: Michelin Guide, checked 2 October 2026.
// Google ratings: Google Maps, checked 2 October 2026.
// Prices: each restaurant's own website where published, otherwise recent reviews
// and booking sites (see sourceType and source). Prices are per person, before service.
//
// Fields (one line per restaurant):
//   id          a unique number (never reuse one)
//   name        restaurant name
//   area        London neighbourhood
//   address     full address, also used for the Google Maps link
//   stars       Michelin stars: 1, 2 or 3
//   cat         cuisine (Michelin's label); a new name creates a new filter button
//   rating      Google rating out of 5, or null
//   reviews     number of Google reviews, or null
//   dinner      dinner price per person in £, or null if not confirmed
//   dinnerType  "menu" (tasting or set menu), "main" (typical à la carte main course)
//               or "spend" (typical spend per person at a sharing-plates restaurant)
//   dinnerNote  what the dinner price covers
//   wine        cheapest wine pairing in £, or null if none or not confirmed
//   sourceType  "site" (restaurant's own website), "press" (review or booking site) or "none"
//   source      link to where the price came from
//   website     restaurant's website
//   lat, lng    map position (from the Michelin Guide)
//   placeId     Google place ID, used to load the restaurant's photo
//   status      only for restaurants no longer starred: "lost", "closed" or "changed"
//   formerStars, statusNote   stars it used to hold and what happened
//   change      recent star change: "new" (first star), "up" (gained a star) or "down" (lost a star)
//   changeNote, changeDate   what changed and when (year-month of the Michelin Guide announcement)
//   lunch, lunchType, lunchNote, lunchWine, lunchSource, lunchSourceType
//               the same as the dinner fields, for the lunch menu (lunchNoteZh in Chinese)
//   noLunch     true when the restaurant doesn't serve lunch
// Keep the comma at the end of every line.

window.RESTAURANTS = [
  {id: 1, name: "Mauro Colagreco at Raffles London at The OWO", area: "Whitehall", address: "Whitehall, London, SW1A 2BX", stars: 1, cat: "Modern Cuisine", rating: 4.7, reviews: 91, dinner: 175, dinnerType: "menu", dinnerNote: "Land & Sea tasting menu, 5 courses", wine: 125, source: "https://www.thefork.co.uk/restaurant/mauro-colagreco-at-raffles-london-at-the-owo-r819729/menu", sourceType: "press", website: "https://www.raffles.com/london/dining/mauro-colagreco/", lat: 51.5053846, lng: -0.1263389, placeId: "ChIJs8xCnzIFdkgR_zipkqUZols", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 65, lunchType: "menu", lunchSource: "https://www.thefork.co.uk/restaurant/mauro-colagreco-at-raffles-london-at-the-owo-r819729/menu", lunchSourceType: "press", lunchNote: "Lunch menu, 3 courses"},
  {id: 2, name: "Quilon", area: "Westminster", address: "Taj 51 Hotel, 41 Buckingham Gate, Westminster, London, SW1E 6AF", stars: 1, cat: "Indian", rating: 4.4, reviews: 1253, dinner: 135, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 72, source: "https://quilon.co.uk/files/7355/Quilon_tasting_menu.pdf", sourceType: "site", website: "https://www.quilon.co.uk/", lat: 51.4987577, lng: -0.1375764, placeId: "ChIJu3jc0d4EdkgRmVLp_Cwwti4", lunch: 42, lunchType: "menu", lunchSource: "https://www.squaremeal.co.uk/restaurants/quilon_377", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses (price from January 2025)"},
  {id: 3, name: "Wild Honey St James", area: "St James's", address: "8 Pall Mall, St James's, London, SW1Y 5NG", stars: 1, cat: "Modern British", rating: 4.4, reviews: 1060, dinner: 98, dinnerType: "menu", dinnerNote: "3 courses", wine: null, source: "https://wildhoneystjames.com/menus-wild-honey/", sourceType: "site", website: "https://www.wildhoneystjames.co.uk/", lat: 51.5074626, lng: -0.1321565, placeId: "ChIJCXHRB9EEdkgRrOgHyE2YKbs", lunch: 37, lunchType: "main", lunchSource: "https://www.thefork.com/restaurant/wild-honey-st-james-r600659/menu", lunchSourceType: "press", lunchNote: "À la carte lunch, mains about £28–£46"},
  {id: 4, name: "Michael Caines at The Stafford", area: "St James's", address: "16-18 St James's Place, St James's, London, SW1A 1NJ", stars: 1, cat: "Modern Cuisine", rating: 4.6, reviews: 40, dinner: 95, dinnerType: "menu", dinnerNote: "Discovery menu, 5 courses", wine: null, source: "https://thestaffordlondon.com/michael-caines-at-the-stafford/", sourceType: "site", website: "https://thestaffordlondon.com/michael-caines-at-the-stafford/", lat: 51.5057705, lng: -0.1404344, placeId: "ChIJE7N9g70FdkgROu5U4NT5b5A", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 48, lunchType: "menu", lunchSource: "https://thestaffordlondon.com/michael-caines-at-the-stafford/", lunchSourceType: "site", lunchNote: "Weekly lunch menu, 3 courses (4 courses £58)"},
  {id: 5, name: "1890 by Gordon Ramsay", area: "Strand", address: "Strand, London, WC2R 0EU", stars: 1, cat: "French Contemporary", rating: 4.6, reviews: 376, dinner: 155, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: 110, source: "https://www.andyhayler.com/restaurant/1890-by-gordon-ramsay", sourceType: "press", website: "https://www.gordonramsayrestaurants.com/restaurant-1890", lat: 51.5102984, lng: -0.120722, placeId: "ChIJpYnCw78FdkgRoVHfIfSrTas", lunch: 90, lunchType: "menu", lunchSource: "https://www.gordonramsayrestaurants.com/restaurant-1890", lunchSourceType: "site", lunchNote: "Lunch menu, from"},
  {id: 6, name: "Frog by Adam Handling", area: "Covent Garden", address: "34-35 Southampton Street, Covent Garden, London, WC2E 7HG", stars: 1, cat: "Modern Cuisine", rating: 4.7, reviews: 1116, dinner: 199, dinnerType: "menu", dinnerNote: "Tasting menu, 13 courses", wine: 100, source: "https://www.frogbyadamhandling.com/", sourceType: "site", website: "https://www.frogbyadamhandling.com/", lat: 51.51085, lng: -0.12217, placeId: "ChIJww-u68sEdkgR3lqhkcsnvBY", lunch: 100, lunchType: "menu", lunchSource: "https://www.frogbyadamhandling.com/", lunchSourceType: "site", lunchNote: "Shorter lunch menu"},
  {id: 7, name: "A. Wong", area: "Victoria", address: "70 Wilton Road, Victoria, London, SW1V 1DE", stars: 2, cat: "Chinese", rating: 4.3, reviews: 1334, dinner: 220, dinnerType: "menu", dinnerNote: "Tasting menu", wine: null, source: "https://www.mandarinoriental.com/en/london/mayfair/dine/a-wong", sourceType: "press", website: "https://www.awong.co.uk/", lat: 51.4930091, lng: -0.1406558, placeId: "ChIJkQhKHeAEdkgRbgw0TGfq-W8", lunch: null, lunchType: "menu", lunchSource: "https://www.theinfatuation.com/london/reviews/a-wong", lunchSourceType: "press", lunchNote: "Dim sum lunch, à la carte (returns when the Victoria restaurant reopens)"},
  {id: 8, name: "Alex Dilling at Hotel Café Royal", area: "Soho", address: "68 Regent Street, Soho, London, W1B 4DY", stars: 2, cat: "Modern French", rating: 4.3, reviews: 205, dinner: 225, dinnerType: "menu", dinnerNote: "Tasting menu, 8 courses (short menu £165)", wine: 165, source: "https://alexdilling.com/", sourceType: "site", website: "https://alexdilling.com/", lat: 51.5100201, lng: -0.1359557, placeId: "ChIJt8UvMj4FdkgRYv-IhfUpsqg", lunch: 125, lunchType: "menu", lunchSource: "https://alexdilling.com/", lunchSourceType: "site", lunchNote: "Lunch menu, 5 courses · Saturdays"},
  {id: 9, name: "Evelyn's Table", area: "Soho", address: "The Blue Posts, 28 Rupert Street, Soho, London, W1D 6DJ", stars: 1, cat: "Modern Cuisine", rating: 4.9, reviews: 1496, dinner: 140, dinnerType: "menu", dinnerNote: "Tasting menu, 5 courses", wine: null, source: "https://www.theblueposts.co.uk/evelyns-table/", sourceType: "site", website: "https://www.theblueposts.co.uk/evelyns-table/", lat: 51.5111621, lng: -0.1326022, placeId: "ChIJtZpbttMEdkgRl7-te2KdeSg", lunch: 95, lunchType: "menu", lunchSource: "https://www.theblueposts.co.uk/evelyns-table/", lunchSourceType: "site", lunchNote: "Lunch menu, 4 courses · Thu–Sat"},
  {id: 10, name: "The Ritz Restaurant", area: "St James's", address: "150 Piccadilly, St James's, London, W1J 9BR", stars: 2, cat: "Modern British", rating: 4.7, reviews: 1418, dinner: 235, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses (5 courses £215)", wine: 150, source: "https://www.theritzlondon.com/dine-with-us/the-ritz-restaurant/ritz-restaurant-tasting-menus/", sourceType: "site", website: "https://www.theritzlondon.com/the-ritz-restaurant/", lat: 51.5069929, lng: -0.1418453, placeId: "ChIJV8gP0ykFdkgRbsmzJFpywNA", change: "up", changeNote: "Gained its second star", changeDate: "2025-02", lunch: 105, lunchType: "menu", lunchSource: "https://www.theritzlondon.com/offers/three-course-lunch/", lunchSourceType: "site", lunchNote: "Set lunch, 3 courses · Mon–Fri"},
  {id: 11, name: "Veeraswamy", area: "Mayfair", address: "Victory House, 99 Regent Street, Mayfair, London, W1B 4RS", stars: 1, cat: "Indian", rating: 4.3, reviews: 2411, dinner: 95, dinnerType: "menu", dinnerNote: "Gourmet tasting menu", wine: 55, source: "https://www.veeraswamy.com/menu/tasting-menu/", sourceType: "site", website: "https://www.veeraswamy.com/", lat: 51.5099386, lng: -0.1378476, placeId: "ChIJnVRkK9QEdkgRz8uiqq2HfjM", lunch: 34, lunchType: "menu", lunchSource: "https://www.veeraswamy.com/menu/weekend-lunch/", lunchSourceType: "site", lunchNote: "Set lunch, from (weekend lunch 3 courses £52)"},
  {id: 12, name: "Dining Room at The Goring", area: "Belgravia", address: "15 Beeston Place, Belgravia, London, SW1W 0JW", stars: 1, cat: "Traditional British", rating: 4.6, reviews: 452, dinner: null, dinnerType: "menu", dinnerNote: "À la carte (pre-theatre 3 courses £80); prices not confirmed", wine: null, source: "https://www.thegoring.com/", sourceType: "none", website: "https://www.thegoring.com/", lat: 51.497523, lng: -0.1456983, placeId: "ChIJXalKaSEFdkgRFq49_DDicaA", lunch: 49, lunchType: "menu", lunchSource: "https://www.thefork.co.uk/restaurant/the-goring-dining-room-r600825", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses"},
  {id: 13, name: "Gymkhana", area: "Mayfair", address: "42 Albemarle Street, Mayfair, London, W1S 4JH", stars: 2, cat: "Indian", rating: 4.4, reviews: 3572, dinner: 155, dinnerType: "menu", dinnerNote: "Tasting menu", wine: null, source: "https://www.andyhayler.com/restaurant/gymkhana", sourceType: "press", website: "https://gymkhanalondon.com/", lat: 51.5085431, lng: -0.141547, placeId: "ChIJtwn55ikFdkgRAvOuPIWeLM0", lunch: 60, lunchType: "menu", lunchSource: "https://www.opentable.co.uk/r/gymkhana-london", lunchSourceType: "press", lunchNote: "Lunch menu, 4 courses"},
  {id: 14, name: "HIDE", area: "Mayfair", address: "85 Piccadilly, Mayfair, London, W1J 7NB", stars: 1, cat: "Modern British", rating: 4.5, reviews: 4650, dinner: 165, dinnerType: "menu", dinnerNote: "Tasting menu, 8 courses", wine: 115, source: "https://foodism.co.uk/reviews/restaurants/above-hide-piccadilly-restaurant-review/", sourceType: "press", website: "https://hide.co.uk/", lat: 51.5061533, lng: -0.1443531, placeId: "ChIJn1DE_XsFdkgR6NyYk4IWd64", lunch: 58, lunchType: "menu", lunchSource: "https://www.squaremeal.co.uk/restaurants/hide_998", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses · Wed–Sun"},
  {id: 15, name: "Row on 5", area: "Mayfair", address: "5 Savile Row, Mayfair, London, W1S 3PB", stars: 2, cat: "Modern Cuisine", rating: 4.9, reviews: 233, dinner: 250, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 150, source: "https://www.rowon5london.com/", sourceType: "site", website: "https://www.rowon5london.com/", lat: 51.5105221, lng: -0.1397601, placeId: "ChIJu8QEs-8FdkgRE0znNGEGBoQ", change: "up", changeNote: "Gained its second star", changeDate: "2026-02", lunch: 150, lunchType: "menu", lunchSource: "https://www.rowon5london.com/", lunchSourceType: "site", lunchNote: "Lunch menu · Fri–Sat"},
  {id: 16, name: "Ormer Mayfair", area: "Mayfair", address: "Flemings Hotel, 7-12 Half Moon Street, Mayfair, London, W1J 7BH", stars: 1, cat: "Modern British", rating: 4.8, reviews: 533, dinner: 140, dinnerType: "menu", dinnerNote: "Signature tasting menu, 7 courses", wine: 125, source: "https://www.opentable.co.uk/r/ormer-mayfair-london", sourceType: "press", website: "https://www.flemings-mayfair.co.uk/fine-dining-london/ormer-mayfair-restaurant", lat: 51.5065597, lng: -0.1453868, placeId: "ChIJQxoh3SgFdkgRqFi4kGLn29c", lunch: 95, lunchType: "menu", lunchSource: "https://www.thefork.com/restaurant/ormer-mayfair-r614373/menu", lunchSourceType: "press", lunchNote: "Lunch tasting menu, 5 courses"},
  {id: 17, name: "Ikoyi", area: "Strand", address: "180 Strand, Strand, London, WC2R 1EA", stars: 2, cat: "Creative", rating: 4.5, reviews: 1133, dinner: 395, dinnerType: "menu", dinnerNote: "Tasting menu (shorter menu £180)", wine: null, source: "https://ikoyilondon.com/", sourceType: "site", website: "https://ikoyilondon.com/", lat: 51.5123195, lng: -0.1155388, placeId: "ChIJkw2CZtEEdkgRgiNBxbdniHE", lunch: 395, lunchType: "menu", lunchSource: "https://ikoyilondon.com/", lunchSourceType: "site", lunchNote: "Same tasting menu · Wed–Fri (shorter menu £180)"},
  {id: 18, name: "Sabor", area: "Mayfair", address: "35-37 Heddon Street, Mayfair, London, W1B 4BR", stars: 1, cat: "Spanish", rating: 4.6, reviews: 2406, dinner: 112, dinnerType: "menu", dinnerNote: "Feasting menu (or à la carte)", wine: null, source: "https://www.thefork.com/restaurant/sabor-r643943", sourceType: "press", website: "https://www.saborrestaurants.co.uk/", lat: 51.5114463, lng: -0.1394943, placeId: "ChIJoXHzltUEdkgRc7QLGWRren0", lunch: 112, lunchType: "menu", lunchSource: "https://www.thefork.com/restaurant/sabor-r643943", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 19, name: "Ambassadors Clubhouse", area: "Mayfair", address: "25 Heddon Street, Mayfair, London, W1B 4BH", stars: 1, cat: "Indian", rating: 4.7, reviews: 2294, dinner: 100, dinnerType: "menu", dinnerNote: "Feast menu (vegetarian £95)", wine: null, source: "https://www.thefork.com/restaurant/ambassadors-clubhouse-r851257/menu", sourceType: "press", website: "https://ambassadorsclubhouse.com/", lat: 51.5112065, lng: -0.1399315, placeId: "ChIJ9wPPUaQFdkgRV6fcyggxHng", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 36, lunchType: "menu", lunchSource: "https://ambassadorsclubhouse.com/", lunchSourceType: "site", lunchNote: "Set lunch, 2 or 3 courses, from · daily"},
  {id: 20, name: "Mountain", area: "Soho", address: "16-18 Beak Street, Soho, London, W1F 9RD", stars: 1, cat: "Spanish", rating: 4.3, reviews: 1503, dinner: 40, dinnerType: "main", dinnerNote: "À la carte, wood-grilled mains", wine: null, source: "https://mesprestiges.com/en/london/places/mountain-beak-street-soho", sourceType: "press", website: "https://mountainbeakstreet.com/", lat: 51.5120143, lng: -0.1382586, placeId: "ChIJGXGPYsEFdkgRAIIfSSET698", lunch: 40, lunchType: "main", lunchSource: "https://mesprestiges.com/en/london/places/mountain-beak-street-soho", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 21, name: "Humble Chicken", area: "Soho", address: "54 Frith Street, Soho, London, W1D 4SL", stars: 2, cat: "Japanese", rating: 4.7, reviews: 578, dinner: 250, dinnerType: "menu", dinnerNote: "Omakase tasting menu", wine: null, source: "https://www.humblechickenuk.com/", sourceType: "site", website: "https://www.humblechickenuk.com/", lat: 51.5138258, lng: -0.1317621, placeId: "ChIJj2LUnbgFdkgRs__gtpjkPRg", change: "up", changeNote: "Gained its second star", changeDate: "2025-02", lunch: 250, lunchType: "menu", lunchSource: "https://www.humblechickenuk.com/", lunchSourceType: "site", lunchNote: "Same omakase menu"},
  {id: 22, name: "Cornus", area: "Belgravia", address: "27c Eccleston Place, Belgravia, London, SW1W 9NF", stars: 1, cat: "Modern British", rating: 4.7, reviews: 142, dinner: 155, dinnerType: "menu", dinnerNote: "Tasting menu (extended menu £195)", wine: null, source: "https://www.andyhayler.com/restaurant/cornus", sourceType: "press", website: "https://www.cornusrestaurant.co.uk/", lat: 51.4942405, lng: -0.1477227, placeId: "ChIJhTXjCSIFdkgRENUSN1Qxkos", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 55, lunchType: "menu", lunchSource: "https://www.andyhayler.com/restaurant/cornus", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses"},
  {id: 23, name: "Murano", area: "Mayfair", address: "20 Queen Street, Mayfair, London, W1J 5PP", stars: 1, cat: "Italian", rating: 4.6, reviews: 1055, dinner: 155, dinnerType: "menu", dinnerNote: "3 (£95) to 6 courses, choice of dishes", wine: null, source: "https://www.muranolondon.com/", sourceType: "site", website: "https://www.muranolondon.com/", lat: 51.5071742, lng: -0.1472229, placeId: "ChIJTUlS0S4FdkgRAGTHjEn0wF4", lunch: 60, lunchType: "menu", lunchSource: "https://www.muranolondon.com/", lunchSourceType: "site", lunchNote: "Set lunch, 3 courses (2 courses £55)"},
  {id: 24, name: "Aulis", area: "Soho", address: "16 St Anne's Court, Soho, London, W1F 0BF", stars: 1, cat: "Creative British", rating: 4.8, reviews: 222, dinner: 195, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 95, source: "https://www.aulis.co.uk/aulis-london", sourceType: "site", website: "https://www.aulis.co.uk/aulis-london", lat: 51.5143368, lng: -0.1343223, placeId: "ChIJyZd6oCcFdkgR8CXAKet9630", lunch: 195, lunchType: "menu", lunchSource: "https://www.aulis.co.uk/aulis-london", lunchSourceType: "site", lunchNote: "Same tasting menu · Fri–Sat", lunchWine: 95},
  {id: 25, name: "Benares", area: "Mayfair", address: "12a Berkeley Square, Mayfair, London, W1J 6BS", stars: 1, cat: "Indian", rating: 4.4, reviews: 2640, dinner: 135, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 129, source: "https://benaresrestaurant.com/wp-content/uploads/2026/03/Tasting-Menu-Set-Dinner-wef-06.03.26-Copy.pdf", sourceType: "site", website: "https://benaresrestaurant.com/", lat: 51.5097876, lng: -0.1450274, placeId: "ChIJAStk3ysFdkgR8XBBK_CEfuU", lunch: 43, lunchType: "menu", lunchSource: "https://benaresrestaurant.com/menus/set-menu-2/", lunchSourceType: "site", lunchNote: "Set lunch, 2 courses (3 courses £49)"},
  {id: 26, name: "Muse by Tom Aikens", area: "Belgravia", address: "38 Groom Place, Belgravia, London, SW1X 7BA", stars: 1, cat: "Creative", rating: 4.8, reviews: 360, dinner: 195, dinnerType: "menu", dinnerNote: "Tasting menu, 10 courses (6 courses £105)", wine: 90, source: "https://musebytomaikens.co.uk/menu/", sourceType: "site", website: "https://www.musebytomaikens.co.uk/", lat: 51.4994673, lng: -0.1509184, placeId: "ChIJp65UQTAFdkgREFotZ21mwPs", lunch: 105, lunchType: "menu", lunchSource: "https://musebytomaikens.co.uk/menu/", lunchSourceType: "press", lunchNote: "Lunch tasting menu, 6 courses · Thu–Sat"},
  {id: 27, name: "Pavyllon London", area: "Mayfair", address: "Four Seasons Hotel, Hamilton Place, Mayfair, London, W1J 7DR", stars: 1, cat: "French Contemporary", rating: 4.7, reviews: 706, dinner: 148, dinnerType: "menu", dinnerNote: "Pavyllon menu, 6 courses (4 courses £98)", wine: null, source: "https://www.hot-dinners.com/Gastroblog/Test-drive/pavyllon-london-restaurant-review-four-seasons-park-lane", sourceType: "press", website: "https://www.pavyllonlondon.com/", lat: 51.5045981, lng: -0.150181, placeId: "ChIJBfOjfiUFdkgRvsanD9nfpA0", lunch: 55, lunchType: "menu", lunchSource: "https://www.hot-dinners.com/Gastroblog/Test-drive/pavyllon-london-restaurant-review-four-seasons-park-lane", lunchSourceType: "press", lunchNote: "Lunch menu"},
  {id: 28, name: "Labombe by Trivet", area: "Mayfair", address: "COMO Metropolitan London, 19 Old Park Lane, Mayfair, London, W1K 1LB", stars: 1, cat: "Modern Cuisine", rating: 4.9, reviews: 74, dinner: 40, dinnerType: "main", dinnerNote: "À la carte, dishes £26–£40", wine: null, source: "https://www.squaremeal.co.uk/restaurants/labombe-by-trivet_26085", sourceType: "press", website: "https://www.labombe.co.uk/", lat: 51.5050011, lng: -0.1500251, placeId: "ChIJV0irD_MFdkgR6zRi3FNkXQM", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 30, lunchType: "menu", lunchSource: "https://www.labombe.co.uk/", lunchSourceType: "site", lunchNote: "Set lunch, snack and main · Mon–Fri"},
  {id: 29, name: "Sketch, The Lecture Room and Library", area: "Mayfair", address: "9 Conduit Street, Mayfair, London, W1S 2XG", stars: 3, cat: "Modern French", rating: 4.8, reviews: 64, dinner: 225, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: 95, source: "https://www.thefork.com/restaurant/sketch-the-lecture-room-and-library-r820753", sourceType: "press", website: "https://sketch.london/the-lecture-room", lat: 51.5126775, lng: -0.1415369, placeId: "ChIJk4chQY4FdkgRDxmXasfbHlc", lunch: null, lunchType: "menu", lunchSource: "https://www.squaremeal.co.uk/restaurants/sketch-the-lecture-room-library_759", lunchSourceType: "press", lunchNote: "Gourmet Rapide set lunch · Fri–Sat (price not published)"},
  {id: 30, name: "Umu", area: "Mayfair", address: "14-16 Bruton Place, Mayfair, London, W1J 6LX", stars: 1, cat: "Japanese", rating: 4.6, reviews: 1274, dinner: 260, dinnerType: "menu", dinnerNote: "Kaiseki menu", wine: null, source: "https://www.umurestaurant.com/", sourceType: "site", website: "https://www.umurestaurant.com/", lat: 51.5113444, lng: -0.1444006, placeId: "ChIJ9cBDsSsFdkgR79Fc_1y6_cI", lunch: 70, lunchType: "menu", lunchSource: "https://www.umurestaurant.com/menus/lunch-menu", lunchSourceType: "site", lunchNote: "Shokado bento lunch (from £50 vegetarian)"},
  {id: 31, name: "Brooklands by Claude Bosi", area: "Belgravia", address: "The Peninsula Hotel, 1 Grosvenor Place, Belgravia, London, SW1X 7HJ", stars: 2, cat: "Modern Cuisine", rating: 4.3, reviews: 101, dinner: 195, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses (5 courses £175)", wine: 145, source: "https://www.peninsula.com/en/london/hotel-fine-dining/brooklands", sourceType: "press", website: "https://www.peninsula.com/en/london/hotel-fine-dining/brooklands", lat: 51.5017267, lng: -0.1518849, placeId: "ChIJn6GfuNgFdkgRVm_XNMCoaCM", lunch: 58, lunchType: "menu", lunchSource: "https://www.peninsula.com/en/newsroom/london/news/brooklands-by-claude-bosi-launches-new-concorde-lunch-menu", lunchSourceType: "site", lunchNote: "Concorde lunch, 3 courses · Tue–Sat"},
  {id: 32, name: "Sushi Kanesaka", area: "Mayfair", address: "45 Park Lane, Mayfair, London, W1K 1PN", stars: 1, cat: "Japanese", rating: 4.7, reviews: 75, dinner: 420, dinnerType: "menu", dinnerNote: "Omakase, 18–20 courses", wine: 150, source: "https://www.hot-dinners.com/London-restaurants/Mayfair-Belgravia/sushi-kanesaka", sourceType: "press", website: "https://www.dorchestercollection.com/en/london/45-park-lane/restaurants-bars/sushi-kanesaka/", lat: 51.5064815, lng: -0.1517726, placeId: "ChIJz6Z6V5wFdkgRQ9AZGAlIpzU", noLunch: true, lunchNote: "Dinner only"},
  {id: 33, name: "Jamavar", area: "Mayfair", address: "8 Mount Street, Mayfair, London, W1K 3NF", stars: 1, cat: "Indian", rating: 4.1, reviews: 2310, dinner: 130, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 98, source: "https://jamavarrestaurants.com/indian-restaurant-mayfair/", sourceType: "site", website: "https://jamavarrestaurants.com/indian-restaurant-mayfair/", lat: 51.5103041, lng: -0.1484316, placeId: "ChIJmyw0PSwFdkgRTdpWlbA5OmU", lunch: 47, lunchType: "menu", lunchSource: "https://jamavarrestaurants.com/indian-restaurant-mayfair/", lunchSourceType: "site", lunchNote: "Set lunch, 3 courses (4 courses £54)"},
  {id: 34, name: "Hélène Darroze at The Connaught", area: "Mayfair", address: "Carlos Place, Mayfair, London, W1K 2AL", stars: 3, cat: "Modern Cuisine", rating: 4.5, reviews: 937, dinner: 259, dinnerType: "menu", dinnerNote: "Taste of the Season, 7 courses", wine: null, source: "https://theconnaught.wearegifted.co.uk/helene-darrozes-taste-of-the-season", sourceType: "site", website: "https://www.the-connaught.co.uk/restaurants-bars/helene-darroze-at-the-connaught/", lat: 51.510188, lng: -0.1492905, placeId: "ChIJNdaqLSwFdkgRcp3iqGlL6Ek", lunch: 125, lunchType: "menu", lunchSource: "https://reportergourmet.com/en/news/8907-helene-darroze-at-the-connaught-three-michelin-stars-between-france-and-italy-in-london", lunchSourceType: "press", lunchNote: "Midweek lunch, 3 courses"},
  {id: 35, name: "Alain Ducasse at The Dorchester", area: "Mayfair", address: "The Dorchester Hotel, 53 Park Lane, Mayfair, London, W1K 1QA", stars: 3, cat: "French", rating: 4.3, reviews: 652, dinner: 285, dinnerType: "menu", dinnerNote: "Signature tasting menu", wine: 160, source: "https://www.opentable.co.uk/alain-ducasse-at-the-dorchester", sourceType: "press", website: "https://www.alainducasse-dorchester.com/", lat: 51.5073381, lng: -0.152575, placeId: "ChIJDaP2Ky4FdkgR7VspCxVWiDk", lunch: 125, lunchType: "menu", lunchSource: "https://www.alainducasse-dorchester.com/", lunchSourceType: "site", lunchNote: "Set lunch, from"},
  {id: 36, name: "Chishuru", area: "Fitzrovia", address: "3 Great Titchfield Street, Fitzrovia, London, W1W 8AX", stars: 1, cat: "African", rating: 4.6, reviews: 819, dinner: 105, dinnerType: "menu", dinnerNote: "Set dinner menu", wine: null, source: "https://www.chishuru.com/", sourceType: "site", website: "https://www.chishuru.com/", lat: 51.5167307, lng: -0.1399754, placeId: "ChIJbTkU-5obdkgR8MpRXunujW4", lunch: 55, lunchType: "menu", lunchSource: "https://www.chishuru.com/", lunchSourceType: "site", lunchNote: "Set lunch menu"},
  {id: 37, name: "Akoko", area: "Fitzrovia", address: "21 Berners Street, Fitzrovia, London, W1T 3LP", stars: 1, cat: "African", rating: 4.8, reviews: 1005, dinner: 130, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 80, source: "https://akoko.co.uk/", sourceType: "site", website: "https://akoko.co.uk/", lat: 51.5177438, lng: -0.13691, placeId: "ChIJU7uHDYcbdkgRttS28-dNO7E", lunch: 65, lunchType: "menu", lunchSource: "https://akoko.co.uk/", lunchSourceType: "site", lunchNote: "Short lunch menu (full tasting menu £130)", lunchWine: 50},
  {id: 38, name: "Pétrus by Gordon Ramsay", area: "Belgravia", address: "1 Kinnerton Street, Belgravia, London, SW1X 8EA", stars: 1, cat: "French", rating: 4.6, reviews: 1612, dinner: 150, dinnerType: "menu", dinnerNote: "Prestige tasting menu, 6 courses", wine: null, source: "https://www.gordonramsayrestaurants.com/petrus", sourceType: "site", website: "https://www.gordonramsayrestaurants.com/petrus", lat: 51.4995628, lng: -0.1567357, placeId: "ChIJBWbG7DsFdkgRUoGawp2ooK8", lunch: 59, lunchType: "menu", lunchSource: "https://www.gordonramsayrestaurants.com/petrus", lunchSourceType: "site", lunchNote: "Weekday lunch, from"},
  {id: 39, name: "Amaya", area: "Belgravia", address: "Halkin Arcade, 19 Motcomb Street, Belgravia, London, SW1X 8JT", stars: 1, cat: "Indian", rating: 4.3, reviews: 1876, dinner: 75, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 50, source: "https://www.amaya.biz/menu/dinner-tasting-menu/", sourceType: "site", website: "https://www.amaya.biz/", lat: 51.4993036, lng: -0.1571945, placeId: "ChIJp_GF9TsFdkgR-LPVooRUYyE", lunch: 32, lunchType: "menu", lunchSource: "https://www.amaya.biz/menu/lunch-platters/", lunchSourceType: "site", lunchNote: "Lunch platter (5-course favourites menu £55)"},
  {id: 40, name: "The Ninth", area: "Fitzrovia", address: "22 Charlotte Street, Fitzrovia, London, W1T 2NB", stars: 1, cat: "Mediterranean Cuisine", rating: 4.5, reviews: 1539, dinner: 98, dinnerType: "menu", dinnerNote: "Seasonal tasting menu", wine: 70, source: "https://theninthlondon.com/menu/", sourceType: "site", website: "https://www.theninthlondon.com/", lat: 51.5188446, lng: -0.1349237, placeId: "ChIJl9_NdCwbdkgRpKEhBGIYGmU", lunch: 45, lunchType: "menu", lunchSource: "https://theninthlondon.com/menu/", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses (2 courses £39) · Mon–Sat"},
  {id: 41, name: "Pied à Terre", area: "Fitzrovia", address: "34 Charlotte Street, Fitzrovia, London, W1T 2NH", stars: 1, cat: "Creative", rating: 4.3, reviews: 740, dinner: 155, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses (5 courses £135)", wine: 170, source: "https://www.pied-a-terre.co.uk/", sourceType: "site", website: "https://www.pied-a-terre.co.uk/", lat: 51.5191109, lng: -0.1352265, placeId: "ChIJh8IKCiwbdkgRiefHU7gpZfU", lunch: 95, lunchType: "menu", lunchSource: "https://www.pied-a-terre.co.uk/", lunchSourceType: "site", lunchNote: "À la carte, 2 courses (3 courses £120)"},
  {id: 42, name: "64 Goodge Street", area: "Fitzrovia", address: "64 Goodge Street, Fitzrovia, London, W1T 4NF", stars: 1, cat: "French", rating: 4.8, reviews: 304, dinner: 100, dinnerType: "menu", dinnerNote: "3 courses with snacks", wine: null, source: "https://www.opentable.co.uk/r/64-goodge-street-london", sourceType: "press", website: "https://64goodgestreet.co.uk/", lat: 51.5190312, lng: -0.1368487, placeId: "ChIJVVUuwSsbdkgRRSNEGe3BRBU", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 59, lunchType: "menu", lunchSource: "https://www.opentable.co.uk/r/64-goodge-street-london", lunchSourceType: "press", lunchNote: "Lunch menu, 3 courses"},
  {id: 43, name: "Corenucopia by Clare Smyth", area: "Belgravia", address: "18-22 Holbein Place, Belgravia, London, SW1W 8NL", stars: 1, cat: "Traditional British", rating: 4.6, reviews: 100, dinner: 54, dinnerType: "main", dinnerNote: "À la carte", wine: null, source: "https://www.squaremeal.co.uk/restaurants/corenucopia-by-clare-smyth_28184", sourceType: "press", website: "https://www.corenucopia.com/", lat: 51.4902602, lng: -0.1554088, placeId: "ChIJBxZMvIQFdkgRaG_9eyLTRvY", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 54, lunchType: "main", lunchSource: "https://www.squaremeal.co.uk/restaurants/corenucopia-by-clare-smyth_28184", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 44, name: "Dinner by Heston Blumenthal", area: "Knightsbridge", address: "Mandarin Oriental Hyde Park, 66 Knightsbridge, London, SW1X 7LA", stars: 2, cat: "Traditional British", rating: 4.6, reviews: 2560, dinner: 195, dinnerType: "menu", dinnerNote: "Journey Through History, 8 courses (6 courses £155)", wine: null, source: "https://www.dinnerbyheston.co.uk/", sourceType: "site", website: "https://www.dinnerbyheston.co.uk/", lat: 51.5021106, lng: -0.1599147, placeId: "ChIJRzX0mDkFdkgR-qAx8kL982A", lunch: 75, lunchType: "menu", lunchSource: "https://www.dinnerbyheston.co.uk/", lunchSourceType: "site", lunchNote: "Lunch menu, 3 courses"},
  {id: 45, name: "Bonheur by Matt Abé", area: "Mayfair", address: "43 Upper Brook Street, Mayfair, London, W1K 7QR", stars: 2, cat: "Modern Cuisine", rating: 4.4, reviews: 55, dinner: 225, dinnerType: "menu", dinnerNote: "Dream tasting menu, 7 courses (5 courses £195)", wine: null, source: "https://www.hot-dinners.com/Gastroblog/Test-drive/bonheur-matt-abe-restaurant-review-mayfair-london", sourceType: "press", website: "https://www.bonheurbymattabe.com/", lat: 51.5112593, lng: -0.155109, placeId: "ChIJmx5ydgAFdkgRr871ONe-sks", change: "up", changeNote: "New straight in with two stars", changeDate: "2026-02", lunch: 110, lunchType: "menu", lunchSource: "https://www.squaremeal.co.uk/restaurants/bonheur-by-matt-abe_27747", lunchSourceType: "press", lunchNote: "Lunch menu, 3 courses · Thu–Sat"},
  {id: 46, name: "Kitchen Table", area: "Fitzrovia", address: "70 Charlotte Street, Fitzrovia, London, W1T 4QG", stars: 2, cat: "Modern Cuisine", rating: 4.8, reviews: 596, dinner: null, dinnerType: "menu", dinnerNote: "Tasting menu (price not published online)", wine: 175, source: "https://kitchentablelondon.co.uk/", sourceType: "site", website: "https://kitchentablelondon.co.uk/", lat: 51.5203616, lng: -0.13647, placeId: "ChIJ3aa-YCkbdkgRo5LPUQzy0hI", noLunch: true, lunchNote: "Dinner only"},
  {id: 47, name: "Tom Brown at The Capital", area: "Knightsbridge", address: "22-24 Basil Street, Knightsbridge, London, SW3 1AT", stars: 1, cat: "Seafood", rating: 4.4, reviews: 222, dinner: 120, dinnerType: "menu", dinnerNote: "Tasting menu, 6 courses", wine: null, source: "https://www.thefork.com/restaurant/tom-brown-at-the-capital-r601113", sourceType: "press", website: "https://www.tombrownatthecapital.com/", lat: 51.5001262, lng: -0.1615559, placeId: "ChIJcxfV3jgFdkgRPIzugJ79Ki0", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 37, lunchType: "main", lunchSource: "https://www.tombrownatthecapital.com/", lunchSourceType: "site", lunchNote: "À la carte lunch, mains about £29–£46 · Sun–Thu"},
  {id: 48, name: "Portland", area: "Fitzrovia", address: "113 Great Portland Street, Fitzrovia, London, W1W 6QQ", stars: 1, cat: "Modern Cuisine", rating: 4.7, reviews: 891, dinner: 110, dinnerType: "menu", dinnerNote: "Tasting menu (3 courses £95)", wine: null, source: "https://misswidjaja.com/portland-restaurant/", sourceType: "press", website: "https://portlandrestaurant.co.uk/", lat: 51.5198009, lng: -0.1427082, placeId: "ChIJUQmz3dUadkgRGnD2W-pGoFM", lunch: 59, lunchType: "menu", lunchSource: "https://allsetlondon.com/r/portland", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses (2 courses £49) · Tue–Sat"},
  {id: 49, name: "OMA", area: "Borough Market", address: "3 Bedale Street, Borough Market, London, SE1 9AL", stars: 1, cat: "Greek", rating: 4.7, reviews: 2575, dinner: 88, dinnerType: "spend", dinnerNote: "À la carte sharing plates (typical spend per person)", wine: null, source: "https://www.andyhayler.com/restaurant/oma", sourceType: "press", website: "https://www.oma.london/", lat: 51.5053331, lng: -0.0897239, placeId: "ChIJ4co2k5kDdkgROKjVBk6wD8k", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 88, lunchType: "spend", lunchSource: "https://www.andyhayler.com/restaurant/oma", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 50, name: "KOL", area: "Marylebone", address: "9 Seymour Street, Marylebone, London, W1H 7BA", stars: 1, cat: "Mexican", rating: 4.5, reviews: 1025, dinner: 145, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: 90, source: "https://www.charlottecohencooks.co.uk/food-travel/kol-mexican-restaurant-london", sourceType: "press", website: "https://kolrestaurant.com/", lat: 51.5147873, lng: -0.1574918, placeId: "ChIJvfnOCgUbdkgR3FvbixhS2cw", lunch: 145, lunchType: "menu", lunchSource: "https://www.charlottecohencooks.co.uk/food-travel/kol-mexican-restaurant-london", lunchSourceType: "press", lunchNote: "Same tasting menu"},
  {id: 51, name: "Trishna", area: "Marylebone", address: "15-17 Blandford Street, Marylebone, London, W1U 3DG", stars: 1, cat: "Indian", rating: 4.6, reviews: 2352, dinner: 90, dinnerType: "menu", dinnerNote: "Trishna tasting menu, 5 courses", wine: 85, source: "https://www.trishnalondon.com/wp-content/uploads/2024/04/Trishna-Tasting-Menu-2026.pdf", sourceType: "site", website: "https://www.trishnalondon.com/", lat: 51.5183427, lng: -0.1529346, placeId: "ChIJ8fHhiM0adkgR5dxGPhTVlvA", lunch: 80, lunchType: "menu", lunchSource: "https://www.trishnalondon.com/wp-content/uploads/2024/04/Trishna-Tasting-Menu-2026.pdf", lunchSourceType: "press", lunchNote: "Lunch tasting menu, 4 courses"},
  {id: 52, name: "Restaurant St. Barts", area: "City of London", address: "63 Bartholomew Close, City of London, London, EC1A 7BF", stars: 1, cat: "Modern British", rating: 4.8, reviews: 497, dinner: 165, dinnerType: "menu", dinnerNote: "Signature tasting menu (midweek menu £125)", wine: 130, source: "https://restaurant-stbarts.co.uk/food-and-drink/", sourceType: "site", website: "https://www.restaurant-stbarts.co.uk/", lat: 51.5183494, lng: -0.0992235, placeId: "ChIJ921POt8bdkgRwx80KJsqCRk", lunch: 60, lunchType: "menu", lunchSource: "https://www.restaurant-stbarts.co.uk/", lunchSourceType: "site", lunchNote: "Business lunch, 3 courses · Mon–Fri (set lunch £75)"},
  {id: 53, name: "St. JOHN", area: "Smithfield", address: "26 St. John Street, Smithfield, London, EC1M 4AY", stars: 1, cat: "Traditional British", rating: 4.5, reviews: 3228, dinner: 30, dinnerType: "main", dinnerNote: "À la carte, mains about £26–£35", wine: null, source: "https://www.squaremeal.co.uk/restaurants/st-john-smithfield_401", sourceType: "press", website: "https://stjohnrestaurant.com/", lat: 51.520489, lng: -0.1014108, placeId: "ChIJFzO5YVEbdkgR1zdv5_hzZwg", lunch: 30, lunchType: "main", lunchSource: "https://www.squaremeal.co.uk/restaurants/st-john-smithfield_401", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 54, name: "Trivet", area: "Southwark", address: "36 Snowsfields, Southwark, London, SE1 3SU", stars: 2, cat: "Modern Cuisine", rating: 4.5, reviews: 423, dinner: 55, dinnerType: "main", dinnerNote: "À la carte, mains about £50–£60", wine: null, source: "https://www.hardens.com/az/restaurants/london/se1/trivet.htm", sourceType: "press", website: "https://trivetrestaurant.co.uk/", lat: 51.502192, lng: -0.084739, placeId: "ChIJhZkSsNQDdkgRwGJZ7Z2rMjg", lunch: 55, lunchType: "main", lunchSource: "https://www.hardens.com/az/restaurants/london/se1/trivet.htm", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 55, name: "Sollip", area: "Southwark", address: "Unit 1, 8 Melior Street, Southwark, London, SE1 3QP", stars: 1, cat: "Creative", rating: 4.8, reviews: 415, dinner: 135, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: 87, source: "https://www.hardens.com/az/restaurants/london/se1/sollip.htm", sourceType: "press", website: "https://www.sollip.co.uk/", lat: 51.5025583, lng: -0.0846577, placeId: "ChIJsZvatGQDdkgR8-eqk7XdOsw", lunch: 78, lunchType: "menu", lunchSource: "https://www.hardens.com/az/restaurants/london/se1/sollip.htm", lunchSourceType: "press", lunchNote: "Lunch menu, 4 courses"},
  {id: 56, name: "AngloThai", area: "Marylebone", address: "22 Seymour Place, Marylebone, London, W1H 7NL", stars: 1, cat: "Thai", rating: 4.7, reviews: 402, dinner: 125, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 95, source: "https://anglothai.co.uk/menus/", sourceType: "press", website: "https://anglothai.co.uk/", lat: 51.515139, lng: -0.161181, placeId: "ChIJf1zYBOYbdkgRpisa6lDN5es", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 65, lunchType: "menu", lunchSource: "https://anglothai.co.uk/menus/", lunchSourceType: "press", lunchNote: "Lunch tasting menu"},
  {id: 57, name: "Lita", area: "Marylebone", address: "7-9 Paddington Street, Marylebone, London, W1U 5QH", stars: 1, cat: "Mediterranean Cuisine", rating: 4.3, reviews: 599, dinner: 50, dinnerType: "main", dinnerNote: "À la carte sharing plates, mains about £37–£66", wine: null, source: "https://www.designmynight.com/london/blog/lita-marylebone-review", sourceType: "press", website: "https://litamarylebone.com/", lat: 51.520828, lng: -0.1526149, placeId: "ChIJpyhiLAAbdkgRGUaeAOxxRLc", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 50, lunchType: "main", lunchSource: "https://www.designmynight.com/london/blog/lita-marylebone-review", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 58, name: "Restaurant Gordon Ramsay", area: "Chelsea", address: "68-69 Royal Hospital Road, Chelsea, London, SW3 4HP", stars: 3, cat: "French", rating: 4.4, reviews: 1874, dinner: 210, dinnerType: "menu", dinnerNote: "Menu Prestige (Carte Blanche £260)", wine: null, source: "https://www.andyhayler.com/restaurant/gordon-ramsay", sourceType: "press", website: "https://www.gordonramsayrestaurants.com/restaurant-gordon-ramsay/", lat: 51.4854381, lng: -0.1621766, placeId: "ChIJkUBQqPAFdkgRtPhH7EIvzJU", lunch: 125, lunchType: "menu", lunchSource: "https://www.opentable.com/restaurant-gordon-ramsay", lunchSourceType: "press", lunchNote: "Weekday lunch menu · Tue–Fri"},
  {id: 59, name: "Luca", area: "Clerkenwell", address: "88 St John Street, Clerkenwell, London, EC1M 4EH", stars: 1, cat: "Italian", rating: 4.5, reviews: 1811, dinner: 95, dinnerType: "menu", dinnerNote: "Chef's menu (or à la carte)", wine: null, source: "https://www.charlottecohencooks.co.uk/food-travel/luca-london-lunch-review", sourceType: "press", website: "https://luca.restaurant/", lat: 51.5223158, lng: -0.1018292, placeId: "ChIJpyQHEFEbdkgR1KctxC2Recc", lunch: 34, lunchType: "menu", lunchSource: "https://www.charlottecohencooks.co.uk/food-travel/luca-london-lunch-review", lunchSourceType: "press", lunchNote: "Bar lunch, 2 courses (3 courses £42)"},
  {id: 60, name: "Elystan Street", area: "Chelsea", address: "43 Elystan Street, Chelsea, London, SW3 3NT", stars: 1, cat: "Modern British", rating: 4.6, reviews: 686, dinner: 165, dinnerType: "menu", dinnerNote: "Tasting menu, 6 courses (3 courses £95)", wine: null, source: "https://www.elystanstreet.com/", sourceType: "site", website: "https://www.elystanstreet.com/", lat: 51.4915449, lng: -0.1675485, placeId: "ChIJyYH9U2oFdkgRCr9oJuLmHiA", lunch: 45, lunchType: "menu", lunchSource: "https://www.tripadvisor.co.uk/Restaurant_Review-g186338-d11672129-Reviews-Elystan_Street-London_England.html", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses · Mon–Sat"},
  {id: 61, name: "Restaurant Gordon Ramsay High", area: "City of London", address: "60th Floor, 22 Bishopsgate, City of London, London, EC2N 4BQ", stars: 1, cat: "Modern Cuisine", rating: 4.5, reviews: 112, dinner: 250, dinnerType: "menu", dinnerNote: "Surprise tasting menu", wine: 160, source: "https://www.hot-dinners.com/Gastroblog/Test-drive/restaurant-gordon-ramsay-high-review-22-bishopsgate-london", sourceType: "press", website: "https://www.gordonramsayrestaurants.com/high/bishopsgate/", lat: 51.5144387, lng: -0.0834119, placeId: "ChIJ_0dDsFIDdkgRhVvXnvnF49A", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", noLunch: true, lunchNote: "Dinner only"},
  {id: 62, name: "Restaurant Story", area: "Southwark", address: "199 Tooley Street, Southwark, London, SE1 2JX", stars: 2, cat: "Modern Cuisine", rating: 4.7, reviews: 934, dinner: 275, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: null, source: "https://restaurantstory.co.uk/", sourceType: "site", website: "https://restaurantstory.co.uk/", lat: 51.5028085, lng: -0.077787, placeId: "ChIJcb5nuUUDdkgRp2TnVMSprT0", lunch: 175, lunchType: "menu", lunchSource: "https://restaurantstory.co.uk/", lunchSourceType: "site", lunchNote: "Lunch menu, 5 courses"},
  {id: 63, name: "Angler", area: "Finsbury", address: "3 South Place, Finsbury, London, EC2M 2AF", stars: 1, cat: "Fish and Seafood", rating: 4.6, reviews: 753, dinner: 155, dinnerType: "menu", dinnerNote: "Signature tasting menu, 7 courses (Taste of Angler £90)", wine: null, source: "https://www.opentable.co.uk/r/angler-london", sourceType: "press", website: "https://www.anglerrestaurant.com/", lat: 51.5189674, lng: -0.086521, placeId: "ChIJU07oP6wcdkgRxecDS1lBdlc", lunch: 60, lunchType: "menu", lunchSource: "https://www.anglerrestaurant.com/", lunchSourceType: "site", lunchNote: "Express lunch, served within an hour · Tue–Fri"},
  {id: 64, name: "Kerfield Arms", area: "Camberwell", address: "16 Grove Lane, Camberwell, London, SE5 8SY", stars: 1, cat: "Modern British", rating: 4.7, reviews: 297, dinner: 27, dinnerType: "main", dinnerNote: "À la carte pub menu", wine: null, source: "https://www.squaremeal.co.uk/restaurants/the-kerfield-arms_27065", sourceType: "press", website: "https://www.thekerfieldarms.co.uk/", lat: 51.4730004, lng: -0.0898627, placeId: "ChIJExecbgADdkgRfhIBRRGzEb8", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 12, lunchType: "menu", lunchSource: "https://www.artefactmagazine.com/2026/06/17/the-12-michelin-star-meal-hidden-inside-a-london-pub/", lunchSourceType: "press", lunchNote: "Midweek lunch special (à la carte also served)"},
  {id: 65, name: "Galvin La Chapelle", area: "Shoreditch", address: "35 Spital Square, Shoreditch, London, E1 6DY", stars: 1, cat: "French", rating: 4.6, reviews: 3120, dinner: 155, dinnerType: "menu", dinnerNote: "Tasting menu, 8 courses", wine: null, source: "https://www.thefork.com/restaurant/galvin-la-chapelle-r632801/menu", sourceType: "press", website: "https://galvinrestaurants.com/", lat: 51.520295, lng: -0.0783716, placeId: "ChIJg5eH2LMcdkgRIY4RDHmB8RA", lunch: 49, lunchType: "menu", lunchSource: "https://allsetlondon.com/r/galvin-la-chapelle", lunchSourceType: "press", lunchNote: "Set lunch, 2 courses (3 courses £55) · Mon–Sat"},
  {id: 66, name: "Trinity", area: "Clapham", address: "4 The Polygon, Clapham, London, SW4 0JG", stars: 1, cat: "Modern Cuisine", rating: 4.8, reviews: 1092, dinner: 140, dinnerType: "menu", dinnerNote: "Dinner tasting menu", wine: null, source: "https://www.opentable.co.uk/trinity-london", sourceType: "press", website: "https://trinityrestaurant.co.uk/", lat: 51.4635167, lng: -0.14151, placeId: "ChIJHdc2Rq0FdkgRNkQ9YeRS1ig", lunch: 75, lunchType: "menu", lunchSource: "https://www.opentable.co.uk/trinity-london", lunchSourceType: "press", lunchNote: "Lunch tasting menu"},
  {id: 67, name: "Plates London", area: "Shoreditch", address: "320 Old Street, Shoreditch, London, EC1V 9DR", stars: 1, cat: "Vegan", rating: 4.8, reviews: 617, dinner: 125, dinnerType: "menu", dinnerNote: "Discovery menu, 10 courses (vegan)", wine: 75, source: "https://plates-london.com/plant-based-restaurant-london/", sourceType: "site", website: "https://plates-london.com/plant-based-restaurant-london/", lat: 51.5265904, lng: -0.0819587, placeId: "ChIJ8UUT9LscdkgRUpwod2WlxEg", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 109, lunchType: "menu", lunchSource: "https://plates-london.com/plant-based-restaurant-london/", lunchSourceType: "site", lunchNote: "Signature menu, 8 courses", lunchWine: 75},
  {id: 68, name: "Legado", area: "Shoreditch", address: "1C Montacute Yards, 185-186 Shoreditch High Street, London, E1 6HU", stars: 1, cat: "Spanish", rating: 4.5, reviews: 463, dinner: 125, dinnerType: "spend", dinnerNote: "À la carte Spanish sharing plates (typical spend per person)", wine: null, source: "https://www.hot-dinners.com/Gastroblog/Test-drive/legado-restaurant-review-nieves-barragan-shoreditch-london", sourceType: "press", website: "https://www.legadorestaurants.com/", lat: 51.5244168, lng: -0.0783756, placeId: "ChIJie6cOxsddkgRwMuFOl3itdI", change: "new", changeNote: "Gained its first star", changeDate: "2026-02", lunch: 125, lunchType: "spend", lunchSource: "https://www.hot-dinners.com/Gastroblog/Test-drive/legado-restaurant-review-nieves-barragan-shoreditch-london", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 69, name: "Brat", area: "Shoreditch", address: "4 Redchurch Street, Shoreditch, London, E1 6JL", stars: 1, cat: "Traditional British", rating: 4.5, reviews: 2517, dinner: 30, dinnerType: "main", dinnerNote: "À la carte, mains about £28–£70", wine: null, source: "https://mesprestiges.com/en/london/places/brat-shoreditch", sourceType: "press", website: "https://bratrestaurant.co.uk/", lat: 51.5242457, lng: -0.0769561, placeId: "ChIJ7XVltrAcdkgRISmskLX7lbw", lunch: 30, lunchType: "main", lunchSource: "https://mesprestiges.com/en/london/places/brat-shoreditch", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 70, name: "The Clove Club", area: "Shoreditch", address: "Shoreditch Town Hall, 380 Old Street, Shoreditch, London, EC1V 9LT", stars: 2, cat: "Creative", rating: 4.6, reviews: 1135, dinner: 285, dinnerType: "menu", dinnerNote: "Classic tasting menu (short menu £225)", wine: null, source: "https://gifts.thecloveclub.com/products/tasting-menu-2", sourceType: "site", website: "https://www.thecloveclub.com/", lat: 51.5271054, lng: -0.0793371, placeId: "ChIJkbGoX7ocdkgRgfrpjeC7xzM", lunch: 95, lunchType: "menu", lunchSource: "https://www.thecloveclub.com/menus", lunchSourceType: "site", lunchNote: "Lunch menu, 3 courses · Wed–Sat (lunch tasting menu £185)"},
  {id: 71, name: "Cycene", area: "Shoreditch", address: "Blue Mountain School, 9 Chance Street, Shoreditch, London, E2 7JB", stars: 1, cat: "Modern Cuisine", rating: 4.8, reviews: 332, dinner: 195, dinnerType: "menu", dinnerNote: "Tasting menu, 9 courses", wine: 140, source: "https://www.bluemountain.school/cycene", sourceType: "press", website: "https://www.bluemountain.school/cycene", lat: 51.5244846, lng: -0.0752056, placeId: "ChIJsxeqTo4ddkgRJq0WOb2AgvE", lunch: null, lunchType: "menu", lunchSource: "https://www.bluemountain.school/cycene", lunchSourceType: "site", lunchNote: "Saturday luncheon set menu (price not published)"},
  {id: 72, name: "Kitchen W8", area: "Kensington", address: "11-13 Abingdon Road, Kensington, London, W8 6AH", stars: 1, cat: "Modern Cuisine", rating: 4.5, reviews: 914, dinner: 120, dinnerType: "menu", dinnerNote: "Tasting menu", wine: null, source: "https://www.kitchenw8.com/", sourceType: "site", website: "https://www.kitchenw8.com/", lat: 51.4990858, lng: -0.1969096, placeId: "ChIJ1-By1fMPdkgRHFSgAdcS41Y", lunch: 49.5, lunchType: "menu", lunchSource: "https://www.kitchenw8.com/", lunchSourceType: "site", lunchNote: "Set lunch, 3 courses · Mon–Sat"},
  {id: 73, name: "The Harwood Arms", area: "Fulham", address: "Walham Grove, Fulham, London, SW6 1QP", stars: 1, cat: "Modern British", rating: 4.6, reviews: 1713, dinner: 79, dinnerType: "menu", dinnerNote: "2 (£64) or 3 courses", wine: null, source: "https://harwoodarms.com/", sourceType: "site", website: "https://harwoodarms.com/", lat: 51.4828975, lng: -0.1964558, placeId: "ChIJYbZdgoUPdkgRrBtAYcMgkBc", lunch: 79, lunchType: "menu", lunchSource: "https://harwoodarms.com/", lunchSourceType: "site", lunchNote: "Same menu, 3 courses (2 courses £64)"},
  {id: 74, name: "The Ledbury", area: "Notting Hill", address: "127 Ledbury Road, Notting Hill, London, W11 2AQ", stars: 3, cat: "Modern Cuisine", rating: 4.7, reviews: 1711, dinner: 285, dinnerType: "menu", dinnerNote: "Tasting menu, 8 courses", wine: null, source: "https://joinpearl.co/blogs/planning-a-visit-to-the-ledbury-in-2026", sourceType: "press", website: "https://www.theledbury.com/", lat: 51.5166662, lng: -0.2000272, placeId: "ChIJe29QNB0QdkgR5Kkx_0-jdo4", lunch: 180, lunchType: "menu", lunchSource: "https://joinpearl.co/blogs/planning-a-visit-to-the-ledbury-in-2026", lunchSourceType: "press", lunchNote: "Lunch tasting menu, 6 courses · Fri–Sat (8 courses £200)"},
  {id: 75, name: "Dorian", area: "Notting Hill", address: "105 Talbot Road, Notting Hill, London, W11 2AT", stars: 1, cat: "Modern British", rating: 3.8, reviews: 763, dinner: 38, dinnerType: "main", dinnerNote: "À la carte, mains from £35", wine: null, source: "https://www.squaremeal.co.uk/restaurants/dorian_24162", sourceType: "press", website: "https://www.dorianrestaurant.com/", lat: 51.5166259, lng: -0.2006009, placeId: "ChIJR1l41mURdkgRZuhK2hbBxRM", lunch: 38, lunchType: "main", lunchSource: "https://www.squaremeal.co.uk/restaurants/dorian_24162", lunchSourceType: "press", lunchNote: "Same à la carte menu at lunch"},
  {id: 76, name: "CORE by Clare Smyth", area: "Notting Hill", address: "92 Kensington Park Road, Notting Hill, London, W11 2PN", stars: 3, cat: "Modern British", rating: 4.7, reviews: 1654, dinner: 275, dinnerType: "menu", dinnerNote: "Core Seasons tasting menu (Core Classics £265)", wine: 175, source: "https://corebyclaresmyth.com/menus/", sourceType: "site", website: "https://www.corebyclaresmyth.com/", lat: 51.5126689, lng: -0.2030649, placeId: "ChIJVVU8V-IPdkgRzKjRtNrdvDw", lunch: 205, lunchType: "menu", lunchSource: "https://www.enprimeurclub.com/guide/dining-at-core-by-clare-smyth-restaurant-in-london", lunchSourceType: "press", lunchNote: "À la carte lunch · Thu–Sat"},
  {id: 77, name: "Caractère", area: "Notting Hill", address: "209 Westbourne Park Road, Notting Hill, London, W11 1EA", stars: 1, cat: "European Contemporary", rating: 4.8, reviews: 425, dinner: null, dinnerType: "menu", dinnerNote: "Tasting and à la carte menus (prices not confirmed)", wine: null, source: "https://www.caractererestaurant.com/", sourceType: "none", website: "https://www.caractererestaurant.com/", lat: 51.517865, lng: -0.2008184, placeId: "ChIJEbr-hcMRdkgR-hV6o35EUno", change: "new", changeNote: "Gained its first star", changeDate: "2025-02", lunch: 65, lunchType: "menu", lunchSource: "https://www.caractererestaurant.com/", lunchSourceType: "site", lunchNote: "Lunch menu, 3 courses", lunchWine: 50},
  {id: 78, name: "Da Terra", area: "Bethnal Green", address: "Town Hall Hotel, 8 Patriot Square, Bethnal Green, London, E2 9NF", stars: 2, cat: "Creative", rating: 4.8, reviews: 521, dinner: 275, dinnerType: "menu", dinnerNote: "Tasting menu (short menu £190)", wine: 160, source: "https://daterra.co.uk/", sourceType: "site", website: "https://daterra.co.uk/", lat: 51.530411, lng: -0.05607, placeId: "ChIJn-wx7LQddkgRMWv5bVEiEfQ", lunch: 110, lunchType: "menu", lunchSource: "https://daterra.co.uk/", lunchSourceType: "site", lunchNote: "Set lunch, 3 courses · Thu–Sat"},
  {id: 79, name: "Behind", area: "London Fields", address: "20 Sidworth Street, London Fields, London, E8 3SD", stars: 1, cat: "Fish and Seafood", rating: 4.7, reviews: 787, dinner: 125, dinnerType: "menu", dinnerNote: "Tasting menu, 10 courses", wine: 88, source: "https://www.behindrestaurant.co.uk/", sourceType: "site", website: "https://www.behindrestaurant.co.uk/", lat: 51.5392307, lng: -0.0575568, placeId: "ChIJdyD4g3MddkgRu4WVVDnjZv8", lunch: 64, lunchType: "menu", lunchSource: "https://www.behindrestaurant.co.uk/", lunchSourceType: "site", lunchNote: "Lunch menu, 6 courses · Thu–Fri", lunchWine: 64},
  {id: 80, name: "Chez Bruce", area: "Wandsworth", address: "2 Bellevue Road, Wandsworth, London, SW17 7EG", stars: 1, cat: "French", rating: 4.8, reviews: 1324, dinner: 98.5, dinnerType: "menu", dinnerNote: "3 courses, choice of dishes", wine: null, source: "https://www.chezbruce.co.uk/booking/prices/", sourceType: "site", website: "https://www.chezbruce.co.uk/", lat: 51.4464026, lng: -0.1653296, placeId: "ChIJFTMRjekFdkgRNMUgOPPr5VY", lunch: 48.5, lunchType: "menu", lunchSource: "https://www.chezbruce.co.uk/booking/prices/", lunchSourceType: "site", lunchNote: "Weekday set lunch, 3 courses · Tue–Fri (standard lunch £68.50)"},
  {id: 81, name: "Casa Fofō", area: "Dalston", address: "158 Sandringham Road, Dalston, London, E8 2HS", stars: 1, cat: "Modern Cuisine", rating: 4.7, reviews: 677, dinner: 76, dinnerType: "menu", dinnerNote: "Tasting menu, 7 courses", wine: 58, source: "https://www.opentable.com/r/casa-fofo-london", sourceType: "press", website: "https://www.casafofolondon.co.uk/", lat: 51.5499681, lng: -0.0641532, placeId: "ChIJq_N9NKgddkgRPmF9XapQArk", lunch: 76, lunchType: "menu", lunchSource: "https://www.casafofolondon.co.uk/", lunchSourceType: "press", lunchNote: "Same tasting menu · Sat–Sun"},
  {id: 82, name: "River Café", area: "Hammersmith", address: "Thames Wharf, Rainville Road, Hammersmith, London, W6 9HA", stars: 1, cat: "Italian", rating: 4.2, reviews: 2116, dinner: 66, dinnerType: "main", dinnerNote: "À la carte, mains about £64–£68", wine: null, source: "https://www.andyhayler.com/restaurant/river-cafe", sourceType: "press", website: "https://www.rivercafe.co.uk/", lat: 51.4841179, lng: -0.2243521, placeId: "ChIJxxa_ELAPdkgRF2wx7RLroiY", lunch: 65, lunchType: "menu", lunchSource: "https://www.rivercafe.co.uk/", lunchSourceType: "site", lunchNote: "Set lunch, 2 courses and dolci (3 courses £80)"},
  {id: 83, name: "La Trompette", area: "Chiswick", address: "3-7 Devonshire Road, Chiswick, London, W4 2EU", stars: 1, cat: "Modern British", rating: 4.7, reviews: 1029, dinner: 95, dinnerType: "menu", dinnerNote: "3 courses, choice of 6", wine: null, source: "https://www.thefork.co.uk/restaurant/la-trompette-r755764/menu", sourceType: "press", website: "https://www.latrompette.co.uk/", lat: 51.491995, lng: -0.2558505, placeId: "ChIJgaR1WkAOdkgRh32MzysCr2Y", lunch: 45, lunchType: "menu", lunchSource: "https://www.latrompette.co.uk/general-info/prices/", lunchSourceType: "press", lunchNote: "Set lunch, 3 courses (standard lunch £65)"},
  {id: 84, name: "Dysart Petersham", area: "Richmond", address: "135 Petersham Road, Richmond, London, TW10 7AA", stars: 1, cat: "Modern Cuisine", rating: 4.7, reviews: 422, dinner: 165, dinnerType: "menu", dinnerNote: "Tasting menu", wine: 85, source: "https://www.thedysartpetersham.co.uk/", sourceType: "site", website: "https://www.thedysartpetersham.co.uk/", lat: 51.4464604, lng: -0.3001695, placeId: "ChIJDauqLMw0cEERuqNQ5irvxGk", lunch: 75, lunchType: "menu", lunchSource: "https://www.thedysartpetersham.co.uk/", lunchSourceType: "site", lunchNote: "Lunch menu, 3 courses (4 courses £89.50)"},
  // No longer starred: shown greyed out on the site. status is "lost", "closed" or "changed".
  {id: 101, name: "City Social", area: "City of London", stars: 0, formerStars: 1, cat: "Modern Cuisine", status: "lost", statusNote: "Lost its star in February 2025; still open", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null, change: "down", changeNote: "Lost its star", changeDate: "2025-02"},
  {id: 102, name: "Claude Bosi at Bibendum", area: "Chelsea", stars: 0, formerStars: 2, cat: "French", status: "closed", statusNote: "Closed in August 2025", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 103, name: "Club Gascon", area: "Smithfield", stars: 0, formerStars: 1, cat: "French", status: "closed", statusNote: "Closed in March 2026", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 104, name: "Endo at the Rotunda", area: "White City", stars: 0, formerStars: 1, cat: "Japanese", status: "closed", statusNote: "Closed after a fire in September 2025", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 105, name: "The Five Fields", area: "Chelsea", stars: 0, formerStars: 1, cat: "Modern Cuisine", status: "closed", statusNote: "Closed in February 2025", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 106, name: "Humo", area: "Mayfair", stars: 0, formerStars: 1, cat: "Grills", status: "lost", statusNote: "Lost its star in February 2026; now relaunched as Igni", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null, change: "down", changeNote: "Lost its star", changeDate: "2026-02"},
  {id: 107, name: "Kai", area: "Mayfair", stars: 0, formerStars: 1, cat: "Chinese", status: "lost", statusNote: "Lost its star in February 2025; still open", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null, change: "down", changeNote: "Lost its star", changeDate: "2025-02"},
  {id: 108, name: "La Dame de Pic London", area: "Tower Hill", stars: 0, formerStars: 2, cat: "Modern French", status: "closed", statusNote: "Closed in February 2025", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 109, name: "Lyle's", area: "Shoreditch", stars: 0, formerStars: 1, cat: "Modern British", status: "closed", statusNote: "Closed in May 2025", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 110, name: "SOLA", area: "Soho", stars: 0, formerStars: 1, cat: "Californian", status: "changed", statusNote: "Moved to Notting Hill in June 2026; not yet listed in the guide again", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 111, name: "Taku", area: "Mayfair", stars: 0, formerStars: 1, cat: "Japanese", status: "changed", statusNote: "Became Sushi Amamoto London in February 2026; removed from the guide", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 112, name: "Dosa", area: "Mayfair", stars: 0, formerStars: 1, cat: "Korean", status: "closed", statusNote: "Gained a star in February 2025; closed before the 2026 guide", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
  {id: 113, name: "Somssi by Jihun Kim", area: "Mayfair", stars: 0, formerStars: 1, cat: "Korean", status: "closed", statusNote: "Gained a star in February 2026; closed in March 2026 when the chef left", rating: null, reviews: null, dinner: null, dinnerType: "menu", dinnerNote: "", wine: null},
];
